// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

#ifndef PROTOBUF_rpc_2eproto__INCLUDED
#define PROTOBUF_rpc_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace gboost_rpc {
namespace detail {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_rpc_2eproto();
void protobuf_AssignDesc_rpc_2eproto();
void protobuf_ShutdownFile_rpc_2eproto();

class RPCMetaData;

// ===================================================================

class RPCMetaData : public ::google::protobuf::Message {
 public:
  RPCMetaData();
  virtual ~RPCMetaData();

  RPCMetaData(const RPCMetaData& from);

  inline RPCMetaData& operator=(const RPCMetaData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RPCMetaData& default_instance();

  void Swap(RPCMetaData* other);

  // implements Message ----------------------------------------------

  RPCMetaData* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RPCMetaData& from);
  void MergeFrom(const RPCMetaData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 seq = 1;
  inline bool has_seq() const;
  inline void clear_seq();
  static const int kSeqFieldNumber = 1;
  inline ::google::protobuf::uint64 seq() const;
  inline void set_seq(::google::protobuf::uint64 value);

  // required int32 service_id = 2;
  inline bool has_service_id() const;
  inline void clear_service_id();
  static const int kServiceIdFieldNumber = 2;
  inline ::google::protobuf::int32 service_id() const;
  inline void set_service_id(::google::protobuf::int32 value);

  // required int32 method_id = 3;
  inline bool has_method_id() const;
  inline void clear_method_id();
  static const int kMethodIdFieldNumber = 3;
  inline ::google::protobuf::int32 method_id() const;
  inline void set_method_id(::google::protobuf::int32 value);

  // required uint32 message_length = 4;
  inline bool has_message_length() const;
  inline void clear_message_length();
  static const int kMessageLengthFieldNumber = 4;
  inline ::google::protobuf::uint32 message_length() const;
  inline void set_message_length(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:gboost_rpc.detail.RPCMetaData)
 private:
  inline void set_has_seq();
  inline void clear_has_seq();
  inline void set_has_service_id();
  inline void clear_has_service_id();
  inline void set_has_method_id();
  inline void clear_has_method_id();
  inline void set_has_message_length();
  inline void clear_has_message_length();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 seq_;
  ::google::protobuf::int32 service_id_;
  ::google::protobuf::int32 method_id_;
  ::google::protobuf::uint32 message_length_;
  friend void  protobuf_AddDesc_rpc_2eproto();
  friend void protobuf_AssignDesc_rpc_2eproto();
  friend void protobuf_ShutdownFile_rpc_2eproto();

  void InitAsDefaultInstance();
  static RPCMetaData* default_instance_;
};
// ===================================================================


// ===================================================================

// RPCMetaData

// required uint64 seq = 1;
inline bool RPCMetaData::has_seq() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RPCMetaData::set_has_seq() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RPCMetaData::clear_has_seq() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RPCMetaData::clear_seq() {
  seq_ = GOOGLE_ULONGLONG(0);
  clear_has_seq();
}
inline ::google::protobuf::uint64 RPCMetaData::seq() const {
  // @@protoc_insertion_point(field_get:gboost_rpc.detail.RPCMetaData.seq)
  return seq_;
}
inline void RPCMetaData::set_seq(::google::protobuf::uint64 value) {
  set_has_seq();
  seq_ = value;
  // @@protoc_insertion_point(field_set:gboost_rpc.detail.RPCMetaData.seq)
}

// required int32 service_id = 2;
inline bool RPCMetaData::has_service_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RPCMetaData::set_has_service_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RPCMetaData::clear_has_service_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RPCMetaData::clear_service_id() {
  service_id_ = 0;
  clear_has_service_id();
}
inline ::google::protobuf::int32 RPCMetaData::service_id() const {
  // @@protoc_insertion_point(field_get:gboost_rpc.detail.RPCMetaData.service_id)
  return service_id_;
}
inline void RPCMetaData::set_service_id(::google::protobuf::int32 value) {
  set_has_service_id();
  service_id_ = value;
  // @@protoc_insertion_point(field_set:gboost_rpc.detail.RPCMetaData.service_id)
}

// required int32 method_id = 3;
inline bool RPCMetaData::has_method_id() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RPCMetaData::set_has_method_id() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RPCMetaData::clear_has_method_id() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RPCMetaData::clear_method_id() {
  method_id_ = 0;
  clear_has_method_id();
}
inline ::google::protobuf::int32 RPCMetaData::method_id() const {
  // @@protoc_insertion_point(field_get:gboost_rpc.detail.RPCMetaData.method_id)
  return method_id_;
}
inline void RPCMetaData::set_method_id(::google::protobuf::int32 value) {
  set_has_method_id();
  method_id_ = value;
  // @@protoc_insertion_point(field_set:gboost_rpc.detail.RPCMetaData.method_id)
}

// required uint32 message_length = 4;
inline bool RPCMetaData::has_message_length() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void RPCMetaData::set_has_message_length() {
  _has_bits_[0] |= 0x00000008u;
}
inline void RPCMetaData::clear_has_message_length() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void RPCMetaData::clear_message_length() {
  message_length_ = 0u;
  clear_has_message_length();
}
inline ::google::protobuf::uint32 RPCMetaData::message_length() const {
  // @@protoc_insertion_point(field_get:gboost_rpc.detail.RPCMetaData.message_length)
  return message_length_;
}
inline void RPCMetaData::set_message_length(::google::protobuf::uint32 value) {
  set_has_message_length();
  message_length_ = value;
  // @@protoc_insertion_point(field_set:gboost_rpc.detail.RPCMetaData.message_length)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace detail
}  // namespace gboost_rpc

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_rpc_2eproto__INCLUDED
