// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pingpong.proto

#ifndef PROTOBUF_pingpong_2eproto__INCLUDED
#define PROTOBUF_pingpong_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_pingpong_2eproto();
void protobuf_AssignDesc_pingpong_2eproto();
void protobuf_ShutdownFile_pingpong_2eproto();

class Ball;

// ===================================================================

class Ball : public ::google::protobuf::Message {
 public:
  Ball();
  virtual ~Ball();

  Ball(const Ball& from);

  inline Ball& operator=(const Ball& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Ball& default_instance();

  void Swap(Ball* other);

  // implements Message ----------------------------------------------

  Ball* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Ball& from);
  void MergeFrom(const Ball& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 client_id = 1;
  inline bool has_client_id() const;
  inline void clear_client_id();
  static const int kClientIdFieldNumber = 1;
  inline ::google::protobuf::uint32 client_id() const;
  inline void set_client_id(::google::protobuf::uint32 value);

  // required uint64 count = 2;
  inline bool has_count() const;
  inline void clear_count();
  static const int kCountFieldNumber = 2;
  inline ::google::protobuf::uint64 count() const;
  inline void set_count(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:Ball)
 private:
  inline void set_has_client_id();
  inline void clear_has_client_id();
  inline void set_has_count();
  inline void clear_has_count();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 count_;
  ::google::protobuf::uint32 client_id_;
  friend void  protobuf_AddDesc_pingpong_2eproto();
  friend void protobuf_AssignDesc_pingpong_2eproto();
  friend void protobuf_ShutdownFile_pingpong_2eproto();

  void InitAsDefaultInstance();
  static Ball* default_instance_;
};
// ===================================================================

class PingPongTesting_Stub;

class PingPongTesting : public ::google::protobuf::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline PingPongTesting() {};
 public:
  virtual ~PingPongTesting();

  typedef PingPongTesting_Stub Stub;

  static const ::google::protobuf::ServiceDescriptor* descriptor();

  virtual void PingPong(::google::protobuf::RpcController* controller,
                       const ::Ball* request,
                       ::Ball* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::google::protobuf::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::google::protobuf::MethodDescriptor* method,
                  ::google::protobuf::RpcController* controller,
                  const ::google::protobuf::Message* request,
                  ::google::protobuf::Message* response,
                  ::google::protobuf::Closure* done);
  const ::google::protobuf::Message& GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const;
  const ::google::protobuf::Message& GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(PingPongTesting);
};

class PingPongTesting_Stub : public PingPongTesting {
 public:
  PingPongTesting_Stub(::google::protobuf::RpcChannel* channel);
  PingPongTesting_Stub(::google::protobuf::RpcChannel* channel,
                   ::google::protobuf::Service::ChannelOwnership ownership);
  ~PingPongTesting_Stub();

  inline ::google::protobuf::RpcChannel* channel() { return channel_; }

  // implements PingPongTesting ------------------------------------------

  void PingPong(::google::protobuf::RpcController* controller,
                       const ::Ball* request,
                       ::Ball* response,
                       ::google::protobuf::Closure* done);
 private:
  ::google::protobuf::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(PingPongTesting_Stub);
};


// ===================================================================


// ===================================================================

// Ball

// required uint32 client_id = 1;
inline bool Ball::has_client_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Ball::set_has_client_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Ball::clear_has_client_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Ball::clear_client_id() {
  client_id_ = 0u;
  clear_has_client_id();
}
inline ::google::protobuf::uint32 Ball::client_id() const {
  // @@protoc_insertion_point(field_get:Ball.client_id)
  return client_id_;
}
inline void Ball::set_client_id(::google::protobuf::uint32 value) {
  set_has_client_id();
  client_id_ = value;
  // @@protoc_insertion_point(field_set:Ball.client_id)
}

// required uint64 count = 2;
inline bool Ball::has_count() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Ball::set_has_count() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Ball::clear_has_count() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Ball::clear_count() {
  count_ = GOOGLE_ULONGLONG(0);
  clear_has_count();
}
inline ::google::protobuf::uint64 Ball::count() const {
  // @@protoc_insertion_point(field_get:Ball.count)
  return count_;
}
inline void Ball::set_count(::google::protobuf::uint64 value) {
  set_has_count();
  count_ = value;
  // @@protoc_insertion_point(field_set:Ball.count)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_pingpong_2eproto__INCLUDED
